config/routes.rb
Portal1871::Application.routes.draw do
  root :to => 'Pages#home'
  resources :users, :companies, :roles, :resources,
        :needs, :skills, :levels, :memberships

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
end

app/views/pages/edit_profile.html.erb
<!doctype html>
<html>
	<head>
		<title>Edit Your Profile</title>
	</head>
		<body>
			<p class="lead">
			<img src="/app/assets/images/1871-logo.png" />

		</p>
		<h1>Edit Your Profile</h1>
		<div class="profile_avatar">
			<a href="#">User Avatar</a>
			<a href="#"><p>Upload a Photo</p></a>
			<a href="#"><p>Add Gravatar</p></a>
		</div>
		<div class="profile_info-skills">
			<!-- Begin Ruby Text -->
			<p>Full Name: Mike Adeleke</p>
			<p>Email: mike@gmail.com</p>
			<!-- End Ruby Text -->
			<h3>Skills</h3>
			<select>
				<h3>Skills here</h3>
				<!-- Begin skills -->
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<!-- End skills -->
			</select>
			<select>
				<h3>Level</h3>
				<!-- Begin level -->
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<!-- End level -->
			</select>
			<form>
				<input type="submit" value="Add skill">
			</form>
		</div>
		<div class="profile_info-social">
			<form>
				<h3>Social media</h3>
				<!-- social input -->
				<input type="text" name="Facebook"><br>
				<input type="text" name="Twitter"><br>
				<input type="text" name="LinkedIn"><br>
				<input type="text" name="GitHub"><br>
				<input type="text" name="Dribbble"><br>
				<input type="text" name="Other URL"><br>
				<!-- end social input -->
			</form>
		</div>
		<div class="profile_info_company">
			<h3>Companies</h3>
			<select>
				<!-- Begin companies -->
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<option value=""></option>
				<!-- End companies -->
			</select>
		</div>
		<div class="profile_info_describe">
			<textarea> Lorem ipsum fjkdbj dsksjk fsdjkd n dsb ajds dsbdsds dsbssd dskbdsdjsdbd djfhdsds dnbdshdsbhjd cdnbhdsncjdsj dsnbdsjd dcbsdvdjs ewuihiwd sdhdhusdisdn csjbdjsdcvdsbuivsd sjbcvjk vjsvsnbvsbjv snbvns s
			</textarea>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<div class="row">
	<div class="span6">
		<article class="home-article">
			<h1>Welcome to the 1871 Portal!</h1>
			<p>
				1871 is a co-working center for digital startups. Located in the famed Merchandise Mart, the 50,000-square-foot facility provides Chicago startups with affordable workspace and access to mentors, programming, educational resources, potential investors and a community of like-minded entrepreneurs.
			</p>
		</article>
	</div>
	<div class="span6">
		<% if !session[:user_id] %>
		<div class="user-sign-in">
			<h3>Sign In</h3>

			<%= form_tag sessions_url do %>
				<div class="home-input">
				 <%= email_field_tag :email, nil, :placeholder => "Email Address" %>
				</div>
				<div class="home-input">
					<%= password_field_tag :password, nil, placeholder: 'Password' %>
				</div>
				<div class="home-input">
					<input type="submit" value="Sign In">
				</div>
			<% end %>

		</div>
		<div class="user-sign-in">
			<h3>Create an Account</h3>

			<%= form_tag users_url do %>
				<div class="home-input">
					<%= email_field_tag :email, nil, placeholder: 'Email Address' %>
				</div>
				<div class="home-input">
					<%= text_field_tag :first_name, nil, placeholder: 'Full Name' %>
				</div>
				<div class="home-input">
					<%= password_field_tag :password, nil, placeholder: 'Password' %>
				</div>
				<div class="home-input">
					<%= password_field_tag :password_confirmation, nil, placeholder: 'Confirm Email Address' %>
				</div>
				<div class="home-input">
					<input type="submit" value="Sign In">
				</div>
			<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/pages/main.html.erb
<p class="lead">
	<img src="/app/assets/images/1871-logo.png" />

</p>
<div class="announcements_heading">
	<h1>Announcements</h1>
</div>
<section>
	<article>
		<img src="#">
		<h3>Title</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</article>
		<article>
		<img src="#">
		<h3>Title</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</article>
		<article>
		<img src="#">
		<h3>Title</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</article>
</section>

app/views/pages/signup_conform.html.erb
<p class="lead">
	<img src="/app/assets/images/1871-logo.png" />

</p>
<div class="signup-thanks">
	<p>Thank you for signing up!</p>
	<p>Please check your inbox, and click the link to authenticate your neew account!</p>
	<form>
		<input type="submit" value="Back to Home">
	</form>
</div>