config/routes.rb
Portal1871::Application.routes.draw do
  root :to => 'Pages#home'
  resources :users, :companies, :roles, :resources,
        :needs, :skills, :levels, :memberships

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal1871</title>
  <link href='http://fonts.googleapis.com/css?family=Days+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="container">
      <span class="logo">Portal</span>
      <nav>
        <a href="/">Home</a>
        <a href="/users">People</a>
        <a href="#">Companies</a>
        <a href="#">Events</a>
        <a href="#">Office Hours</a>
        <a href="#">Connect</a>
      </nav>
      <div class="welcome">
        <% %>
          <!-- <a href="#" class="sign-in">Sign In</a> -->
        <% %>
          <span class="welcome">
            <a href="#">
                <% if session[:user_id] %>
                  <% @user = User.find(session[:user_id]) %>
                  Welcome,
                  <%= "#{@user.first_name}" %>,
                  <%= gravatar_image_tag(@user.email, :alt => "#{@user.first_name}") %>
                   <%= link_to "Sign Out", session_url, method: 'delete' %>
                <% end %>
            </a>
        </span>
        <% %>
      </div>
    </div>
  </header>
  <div class="container">

<%= yield %>

  </div>
  <footer>
    <div class="container">
      <span>Copyright &copy; 2013</span>
    </div>
  </footer>
</body>
</html>